SET(LAPACK_LIBRARY_DIR "c:/Programme/Intel/MKL721/ia32/lib" CACHE PATH "Ordner in dem die mkl Bibliotheken liegen")
IF(LAPACK_LIBRARY_DIR STREQUAL "")
  MESSAGE("LAPACK_LIBRARY_DIR=${LAPACK_LIBRARY_DIR}")
  MESSAGE(FATAL_ERROR "LAPACK_LIBRARY_DIR is not set")    
ENDIF(LAPACK_LIBRARY_DIR STREQUAL "")

set(LAPACK_LIBRARIES )

find_library(LAPACK_MKL_LAPACK_LIBRARAY
  NAMES mkl_lapack
  PATHS ${LAPACK_LIBRARY_DIR} 
)    
if(LAPACK_MKL_LAPACK_LIBRARAY STREQUAL "LAPACK_MKL_LAPACK_LIBRARAY-NOTFOUND")
  IF(MKL_LAPACK_FIND_REQUIRED)
    message(FATAL_ERROR "mkl_lapack nicht gefunden")
  ELSE(MKL_LAPACK_FIND_REQUIRED)
    message(STATUS "mkl_lapack nicht gefunden")
  ENDIF(MKL_LAPACK_FIND_REQUIRED)
endif(LAPACK_MKL_LAPACK_LIBRARAY STREQUAL "LAPACK_MKL_LAPACK_LIBRARAY-NOTFOUND")   
    
list(APPEND LAPACK_LIBRARIES ${LAPACK_MKL_LAPACK_LIBRARAY})
