# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# compile Fortran with C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/bin/intel64_ia32/ifort.exe
Fortran_FLAGS = /W1 /nologo /fpp /libs:static /threads /O3 /Oy- /D NDEBUG  

Fortran_DEFINES = 

Fortran_INCLUDES = 

